version: '3'
services:
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - redirect_app
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  redirect_mq:
    image: rabbitmq:latest
  redirect_db:
    build:
      args: 
        - USERNAME=${REDIRECT_DB_USERNAME}
        - PASSWORD=${REDIRECT_DB_PASSWORD}
      context: ./db/redirect
      dockerfile: Dockerfile
    volumes:
      - ./data/postgres_redirect:/data/postgres_redirect
  redirect_app:
    environment:
      - REDIRECT_DB_USERNAME=${REDIRECT_DB_USERNAME}
      - REDIRECT_DB_PASSWORD=${REDIRECT_DB_PASSWORD} 
    build:
      context: ./apps/redirect
      dockerfile: Dockerfile
    command: sh docker_start.sh
    depends_on:
      - redirect_mq
      - redirect_db
    volumes:
      - ./apps/redirect:/home/clickonly
volumes:
  redirect_db_vol:
